### ISSUE TITLE
[feat] 회원 정보 수정

### ISSUE THREAD

**Issue by devrokket** [Lucy-Arti/Arti-Server#34]
# Issue

회원 정보를 수정한다. 
[notion ticket](https://www.notion.so/lucy-team/69f2ba58c820463da63a242832068272?pvs=4)

## ❓ About

- 카카오 로그인으로 저장한 이름 및 프로필 사진을 수정한다. 

## ✅ Tasks

- [x] 닉네임 칼럼 추가
- [x] 회원 이름 수정
- [x] 닉네임 해싱
- [x] 프로필 사진 S3 update
- [x] 회원 프로필 사진 수정
