### ISSUE TITLE
[기능] 옷 일반, 스케치 구분해주기

### ISSUE THREAD

**Issue by devrokket** [Lucy-Arti/Arti-Server#38]
# Issue

디자인한 옷을 일반 및 스케치 옷으로 구분한다. 

## ❓ About

- 투표를 스케치 옷만 할 수 있도록 api를 분리한다. 

## ✅ Tasks
- [x] 구분 칼럼 추가
- [x] 옷 불러오기 api 분기처리
- [x] 투표를 스케치만 할 수 있도록 대진 api 수정

**Comment by devrokket** [comment]
완료
