### ISSUE TITLE
[Refactor] 옷 페이지네이션 

### ISSUE THREAD

**Issue by devrokket** [Lucy-Arti/Arti-Server#66]
# Issue

옷 불러오기 페이지네이션

## ❓ About

- ### https://arti-fashion.site/productlist
- 옷 둘러보기 페이지에서 로딩 시간이 오랙 걸리는 문제
- 현재 `ClothesController`에서 옷을 불러오는 API (2차 스프린트 때 옷의 카테고리가 생겨 일러스트와 작품 옷을 구분하여 모두 불러오고 있습니다)
<img width="400" alt="image" src="https://github.com/Lucy-Arti/Arti-Server/assets/96538554/f6eadae9-b349-4bb2-80c0-e2aa238e2566">

```
 @GetMapping("/type/{type}")
    public ResponseEntity<?> getByType(@PathVariable String type) {

        if (!Objects.equals(type, Type.sketch.toString()) && !Objects.equals(type,
            Type.product.toString())) {

            throw BusinessException.from(ErrorCode.CLOTHES_INVALID_TYPE);
        }

        Type requestType = Type.valueOf(type);
        return ResponseEntity.ok(clothesService.getTypeAll(requestType));
    }
```

## ✅ Tasks
- [ ] `ClothesRepository.java` 파일의 `findAllByType` 메소드 수정
- [ ] `ClothesService.java` 파일의 `getTypeAll` 메소드 수정 : 파라미터로 Page를 추가로 받아야 함
- [ ] `ClothesController.java` 파일의 `getByType` 메소드 수정 : 파라미터로 Page를 추가로 받아야 함
